TODO_WebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('todo.urls')),
]

todo/urls.py
from django.urls import path

from todo import views

app_name = 'todo'

urlpatterns = [
    path('list/', views.ToDoListView.as_view(), name='todo-list'),
    path('create/', views.create_todo, name='create_todo'),
    path('edit/<int:pk>/', views.update_todo, name='update'),
    path('delete/<int:pk>/', views.delete_todo, name='delete'),
    path('share/', views.share_todo, name='share_todo'),

]

todo/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class TimeStampModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class ToDo(TimeStampModel):
    ACTIVE = "Active"
    COMPLETED = "Completed"
    STATUS_CHOICES = [
        (ACTIVE, "Active"),
        (COMPLETED, "Completed"),
    ]
    name = models.CharField(max_length=1024, null=True, blank=True)
    user = models.ManyToManyField(User, verbose_name="Created By", related_name="users")
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default=ACTIVE)
    due_date = models.DateField()
    owner = models.ForeignKey(User, related_name="todos", on_delete=models.CASCADE, null=True, blank=True)
    class Meta:
        verbose_name_plural = "To-Dos"

    def __str__(self):
        return self.name


class ToDoLog(TimeStampModel):
    updated_by = models.ForeignKey(User, related_name="todologs", on_delete=models.CASCADE)
    todo = models.ForeignKey(ToDo, related_name="todos", on_delete=models.CASCADE)

    def __str__(self):
        return f"Todo updated by {self.updated_by}"

todo/forms.py
from datetime import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.forms import SelectDateWidget

from todo.models import ToDo


class ToDoFormView(forms.ModelForm):
    due_date = forms.DateField(widget=SelectDateWidget(empty_label="Nothing"))

    class Meta:
        model = ToDo
        exclude = ['user', ]

    def clean_due_date(self):
        due_date = self.cleaned_data.get('due_date')

        if due_date < datetime.today().date():
            raise ValidationError('Please choose correct date')
        return due_date

todo/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db import transaction
from django.http import JsonResponse
from django.shortcuts import render, redirect
# Create your views here.
from django.views.generic import ListView, UpdateView

from todo.forms import ToDoFormView
from todo.models import ToDo, ToDoLog


@login_required(login_url='login/')
@transaction.atomic
def create_todo(request):
    if request.method == 'POST':
        form = ToDoFormView(request.POST)

        if form.is_valid():
            todo = form.save(commit=False)
            todo.owner = request.user
            todo.save()
            todo.user.add(request.user)
            return redirect('/')
        else:
            messages.error(request, f"{form.errors['due_date']}")

        return render(request, 'todo/create_todo.html', {'form': form})
    else:
        form = ToDoFormView()
        return render(request, 'todo/create_todo.html', {'form': form})


@login_required(login_url='login/')
def update_todo(request, pk):
    data = ToDo.objects.get(id=pk)
    if request.method == 'POST':
        data.name = request.POST.get('name')
        data.status = request.POST.get('status')
        data.due_date = request.POST.get('due_date')
        data.save()
        ToDoLog.objects.create(updated_by=request.user, todo=data)
        messages.success(request, 'Your To-Do updated successfully.')
        return redirect('todo:todo-list')
    return render(request, 'todo/edit_todo.html', {'data': data})


class ToDoListView(LoginRequiredMixin, ListView):
    model = ToDo
    template_name = 'todo/todolist.html'
    paginate_by = 20

    def get_queryset(self):
        return ToDo.objects.filter(user=self.request.user).order_by('-id', 'status')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ToDoListView, self).get_context_data()
        context['users'] = User.objects.exclude(username=self.request.user.username)
        context['todo_logs'] = ToDoLog.objects.filter(todo__owner=self.request.user).order_by('-id', 'todo__status')
        return context


def delete_todo(request, pk):
    if request.is_ajax():
        data = ToDo.objects.get(id=pk).delete()
        return JsonResponse({'status': 'success', 'id': pk, 'count': ToDo.objects.count()})
    else:
        msg = "Something went wrong"
        return JsonResponse({'status': 'failed', 'msg': msg})


def share_todo(request):
    if request.method == 'POST':
        user_ids = request.POST.getlist('user_ids')
        todo_id = request.POST.get('todo')

        users = User.objects.filter(id__in=user_ids)

        todo = ToDo.objects.get(id=todo_id)
        for user in users:
            todo.user.add(user)
        messages.success(request, "shared successful.")
        return redirect('/')

templates/todo/create_todo.html
{% extends 'users/index.html' %}



{% block content %}
<form method="post">{% csrf_token %}
    <div class="form-group">
        <label for="name">To-Do Name:</label>
        <input type="text" id="name" value="{{form.name.value|default_if_none:''}}" name="name" class="form-control" aria-describedby="emailHelp" placeholder="Enter To-do Name">
    </div>
    <div class="form-group">
        <label for="status">To-Do Status</label>
        <select id="status" name="status">
            <option value="Active" selected>Active</option>
        </select>
    </div>
    <div class="form-group">
        <label for="due_date">To-Do Ends on:</label>
        <input type="date" id="due_date" name="due_date" class="form-control" aria-describedby="emailHelp" placeholder="Enter To-do Name">
    </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

templates/todo/edit_todo.html
{% extends 'users/index.html' %}


{% block content %}
<form method="post">{% csrf_token %}
    <div class="form-group">
        <label for="name">To-Do Name:</label>
        <input type="text" id="name" value="{{data.name}}" name="name" class="form-control" aria-describedby="emailHelp"
               placeholder="Enter To-do Name">
    </div>
    <div class="form-group">
        <label for="status">To-Do Status</label>
        <select id="status" name="status">
            <option value="Active" {% if data.status==
            'Active' %}selected {% endif %}>Active</option>
            <option value="Completed" {% if data.status==
            'Completed' %}selected {% endif %}>Completed</option>
        </select>
    </div>
    <div class="form-group">
        <label for="due_date">To-Do Ends on:</label>
        <input type="date" id="due_date" name="due_date" value="{{data.due_date|date:'Y-m-d'}}" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

templates/todo/todolist.html
{% extends 'users/index.html' %}

{% block content %}
<div class="text-left"><h3>You can create your todo by clicking <span><a href="{% url 'todo:create_todo' %}">here</a></span>.</h3></div>

{% if page_obj %}
  <div id="todo_block">
    <div class="text-left">
      <h3>Your To-Dos:</h3>
    </div>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Due Date</th>
          <th scope="col">Status</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
      {% for data in page_obj %}
        <tr id="todo_id_{{data.id}}">
          <th scope="row">{{forloop.counter}}</th>
          <td>{{data.name}}</td>
          <td>{{data.due_date}}</td>
          <td>{{data.get_status_display}}</td>
          <td><a href="{% url 'todo:update' data.id %}"><i class="fa fa-edit" style="font-size:24px"></i></a>&nbsp;
              {% if data.owner == request.user %}<a href="#"><i class="fa fa-trash-o my_delete" data-url="{% url 'todo:delete' data.id %}" style="font-size:24px"></i></a>
              <a href="#"><i class="fa fa-share my_share" data-id="{{data.id}}" style="margin-left:5px;font-size:24px"></i></a>{% endif %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  <div class="text-center" style="margin-top: 5%" id="no_todo">
    <p> You don't have any To-Dos in your list.
  </div>
{% endif %}
{% if users %}
  <div class="container-fluid">
    <form method="post" id="formID" action="{% url 'todo:share_todo' %}" >{% csrf_token %}
        <div class="text-left">
          <h3>Users:</h3>
          <div class="text-right">
            <input type="hidden" name="todo" id="todo_share_id" value="">
            <input class="btn btn-primary" id="share_sub" type="submit" value="Share" disabled>
          </div>
        </div>
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Username</th>
              <th scope="col">Share</th>
            </tr>
          </thead>
          <tbody>
          {% for data in users %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td>{{data.username}}</td>
              <td><input type="checkbox" class="my_check_box" name="user_ids" value="{{data.id}}" disabled></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
    </form>
  </div>
{% endif %}

{% if todo_logs %}
  <div>
    <div class="text-left">
      <h3>Your To-Do's Logs:</h3>
    </div>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Due Date</th>
          <th scope="col">Status</th>
          <th scope="col">updated By</th>
        </tr>
      </thead>
      <tbody>
      {% for data in todo_logs %}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td>{{data.todo.name}}</td>
          <td>{{data.todo.due_date}}</td>
          <td>{{data.todo.get_status_display}}</td>
          <td>{{data.updated_by}} </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endif %}
{% endblock %}
{% block extra_js %}
<script>
  $(document).on('click','.my_delete', function (e) {
    e.preventDefault();
    var url = $(this).attr('data-url');

    $.ajax({
    url: url,
    type: 'GET',
      success: function(response) {
        if(response.status == 'success'){
          $("#todo_id_"+response.id).remove();
          if(response.count == 0){
            location.reload();
          }
        }
        else{
          alert(response.msg);
        }
      }
    });
  })

  $(document).on('click', '.my_share', function (e) {
    $('#todo_share_id').val($(this).attr('data-id'));
    $('.my_check_box').attr('disabled',false)

  });

  $(document).on('change', '.my_check_box', function (e) {
    if ($("#formID input:checkbox:checked").length > 0){
      $('#share_sub').attr('disabled',false);
    }
    else{
      $('#share_sub').attr('disabled',true);
    }

  })

</script>
{% endblock extra_js %}