TODO_WebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('todo.urls')),
]

todo/urls.py
from django.urls import path

from todo import views

app_name = 'todo'

urlpatterns = [
    path('list/', views.ToDoListView.as_view(), name='todo-list'),
    path('create/', views.create_todo, name='create_todo'),
    path('edit/<int:pk>/', views.update_todo, name='update'),
    path('delete/<int:pk>/', views.delete_todo, name='delete'),
    path('share/', views.share_todo, name='share_todo'),

]

users/urls.py
from django.contrib import auth
from django.urls import path

from users import views
from users.views import activate

app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.Login, name='login'),
    path('register/', views.signup, name='register'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         activate, name='activate'),
    path('logout/', views.LogoutView, name='logout'),

]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

users/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, get_user_model, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from users.token import account_activation_token
from users.forms import SignupForm


def index(request):
    if request.user.is_authenticated:
        return redirect('todo:todo-list')
    return render(request, 'users/index.html')


@transaction.atomic
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            # save form in the memory not in database
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            # to get the domain of the current site
            current_site = get_current_site(request)
            mail_subject = 'Activation link has been sent to your email id'
            message = render_to_string('users/email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            messages.success(request, 'Please confirm your email address to complete the registration')
            return redirect('users:index')
    else:
        form = SignupForm()
    return render(request, 'users/signup.html', {'form': form})


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Thank you for your email confirmation. Now you can login your account.')
        return redirect('users:login')
    else:
        return HttpResponse('Activation link is invalid!')


def Login(request):
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            form = login(request, user)
            messages.success(request, f' welcome {username} !!')
            return redirect('todo:todo-list')
        else:
            messages.error(request, f'username or password is incorrect.')

    if request.user.is_authenticated:
        return redirect('todo:todo-list')
    form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form, })


def LogoutView(request):
    logout(request)
    return redirect('users:index')

templates/users/email.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,  
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}  

templates/users/index.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="title" content="project">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="language" content="English">
  <meta name="author" content="vinayak sharma">

  <title>{{title}}</title>


  <!-- bootstrap file -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <!-- bootstrap file-->
  {% block extra_css %}{% endblock extra_css %}
  <!-- jQuery -->

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


  <!-- main css -->
  <style>
    *{
      padding: 0;
      margin: 0;
      box-sizing: border-box;
    }
    </style>
  {% block extra_js %} {% endblock extra_js %}
</head>

<body class="container-fluid">


  <header class="row">

    <!-- navbar-->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" class="styleheader" href="{% url 'users:index' %}">TO DO Web App</a>
        </div>
        <div class="collapse navbar-collapse" id="mainNavBar">
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'users:logout' %}"><span class="glyphicon glyphicon-log-out"></span> &nbsp; Logout</a></li>
            {% else %}
            <li><a href="{% url 'users:register' %}"><span class="glyphicon glyphicon-user"></span> &nbsp; Sign up</a></li>
            <li><a href="{% url 'users:login' %}"><span class="glyphicon glyphicon-log-in"></span> &nbsp; Log in</a></li>
            {% endif %}

          </ul>
        </div>
      </div>
    </nav>
  </header>

  <br/>
  <br>
  <br>
  <div class="row container-fluid">
    <!-- message here -->
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %}" role="alert">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}

    {% block start %}
    {% if user.is_authenticated %}
    <div class="text-center"><h1>welcome back {{user.username}}!</h1></div>
    {% else %}
    <div class="text-center"><h1>You have to login first to your account to add TODO.</h1></div>
    {% endif %}
    {% endblock %}

    {% block content %}
    {% endblock %}
  </div>
</body>

</html>

templates/users/login.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block start %}

 <div class="content-section col-md-8 col-md-offset-2">
  <center>
  <form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
    {% csrf_token %}
    <fieldset class="form-group">
      {{ form|crispy}}
    </fieldset>
   <center>
    <button style="background: black; font-size: 2rem; padding:1%; color: white" class="btn btn-outline-info" type="submit"><span class="glyphicon glyphicon-log-in"></span> &nbsp; login</button>
  </center>
  <br/>
  <sub style="text-align: left;"><a href="{% url 'users:register' %}" style="text-decoration: none; color: blue; padding:2%; cursor:pointer; margin-right:2%;">don't have account,sign up</a></sub>
  </form>
</center>
 </div>
{% endblock start %}

templates/users/signup.html
{% extends "users/index.html" %}
{% load crispy_forms_tags %}
{% block start %}

<div class="content-section col-md-8 col-md-offset-2">
  <form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
    {% csrf_token %}
    <fieldset class="form-group">
      {{ form|crispy}}
    </fieldset>
    <center>
      <button style="background: black; padding:2%; font-size: 2rem; color:white;" class="btn btn-outline-info" type="submit"><span class="glyphicon glyphicon-check"></span> &nbsp; sign up</button>
    </center>
    <br />
    <sub><a href="{% url 'users:login' %}" style="text-decoration: none; color: blue; padding:3%; cursor:pointer;">Already have an account ?</a></sub>
  </form>
</div>
{% endblock start %}